<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-R31J20A" ignored="0" name="Default test" tests="3" failures="1" timestamp="29 May 2020 05:57:59 GMT" time="21.843" errors="0">
  <testcase name="loginTest" time="0.008" classname="com.qtpselenium.hybrid.suitea.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="21.144" classname="com.qtpselenium.hybrid.suitea.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Titles did not match. Got title as Zoho - Cloud Software Suite and SaaS Applications for Businesses">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Titles did not match. Got title as Zoho - Cloud Software Suite and SaaS Applications for Businesses
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.qtpselenium.hybrid.keywords.GenericKeywords.assertAll(GenericKeywords.java:215)
at com.qtpselenium.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:63)
at com.qtpselenium.hybrid.suitea.LoginTest.loginTest(LoginTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.0" classname="com.qtpselenium.hybrid.suitea.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
